### PR TITLE
fix(Build): fix build using simple travis pipeline

### PR DESCRIPTION
**Pull request by Tony-Proum**
closes https://github.com/Tony-Proum/sonar-clover/issues/20

### CODE REVIEW

**Comment by Tony-Proum** [comment]
FYI https://community.sonarsource.com/t/plugin-copyright-ownership/3311 . For now, I'm not able to find a legal answer. I don't know if this is a good solution for now. Trying to get more helps with the company I work with.

**Comment by mlschechter** [comment]
Is there any reason to change the license? I'd recommend leaving it as GPL if it's simpler.

**Comment by Tony-Proum** [comment]
@ganncamp could you helps us to understand what's happen and why is this project copyrights had been reset ? 

May be could you show us the right way to deal with this problem ?

**Comment by ganncamp** [comment]
@Tony-Proum I don't have enough context in this comment thread to understand what the problem is. What did you change, how did you change it, and when did it rever?

**Comment by Tony-Proum** [comment]
@ganncamp when I became owner of this project, all files came with this header :
```
/*
 * Sonar Clover Plugin
 * Copyright (C) 2008 ${owner}
  * sonarqube@googlegroups.com
...
```
see https://github.com/Tony-Proum/sonar-clover/commit/ea6c23eb9b3a6a5b09e4405f61f03fd52159d944 
(@ganntest is it one of your test account @ganncamp ? :thinking: ) 

I tried to find the right way to contribute to this project so in my opinion, the first step to reach is to build the project properly. In order to do this, I had to update build tools and to fill the missing copyright informations. But even now, I'm not sure that it's a good think to appropriate those rights. 
is this commit designed to be way to abandon the copyright, or is it an un-achieved piece of work ?

**Comment by ganncamp** [comment]
In fact @Tony-Proum I (yes, that's my test account & making the commit with it was an accident) possibly shouldn't have made that change. In fact, I wish I had been more voluble in the commit comment (darn my previous self!) because I have no memory of the motivation or where I got the syntax. All I do know is that I didn't pull it out of the air or do it while sleepwalking. 

IIWY, I'd revert that change & add a 2nd line: `Copyright (C) 2018 @Tony-Proum`. IANAL but my guess is that such a change would show both good faith and assert your ownership of any new changes.

**Comment by Tony-Proum** [comment]
@ganncamp Thank you for the explanation, I'll revert all unneeded changes I try to work this way.

**Pull request merged**
